_target_: src.datamodule.datamodule_gcd.MyDataModule
batch_size: ${batch_size}
num_workers: 4
collate_fn: src.util.collate_fn.collate_pattern_prediction
defaults:
  - train_dataset: gcd_all
  - val_dataset: gcd_all
  - test_dataset: gcd_all
